version: "3"

server:
  command: "php public/index.php"
  # If you are not using symfony 5.3+ and the new Runtime component:
  # remove the previous `command` line above and uncomment the line below to use the deprecated command.
  # command: "php bin/console baldinof:roadrunner:worker"
  env:
    - APP_RUNTIME: \App\System\Infrastructure\Symfony\Runtime\ChoiceRRRuntime
    - XDEBUG_MODE: debug
    - XDEBUG_TRIGGER: yes

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "./public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    num_workers: 1

logs:
  mode: development
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: debug # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: debug

reload:
  enabled: true
  interval: 1s
  patterns: [".php", ".yaml"]
  services:
    http:
      dirs: ["."]
      recursive: true

rpc:
  listen: tcp://127.0.0.1:6001

# Workflow and activity mesh service.
#
# Drop this section for temporal feature disabling.
#temporal:
#  address: temporal:7233
#  activities:
#    debug: true
