version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./ops/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  # Quality tools
  php_qa-csfixer:
    image: jakzal/phpqa:alpine
    profiles: [ code_quality_fixer, csfixer ]
    working_dir: /project
    volumes:
      - "./:/project"
    command: [ php-cs-fixer, fix, --allow-risky=yes, -vvv ]

  php_qa-csfixer_check:
    image: jakzal/phpqa:alpine
    profiles: [ code_quality, csfixer_check ]
    working_dir: /project
    volumes:
      - "./:/project"
    command: [ php-cs-fixer, fix, --allow-risky=yes, --dry-run ]

  php_qa-rector:
    image: jakzal/phpqa:alpine
    profiles: [ code_quality, rector ]
    working_dir: /project
    volumes:
      - "./:/project"
    command: [ rector ]

  php_qa-rector_check:
    image: jakzal/phpqa:alpine
    profiles: [ code_quality, rector_check]
    working_dir: /project
    volumes:
      - "./:/project"
    command: [ rector, --dry-run ]

  php_qa-phpstan:
    image: jakzal/phpqa:alpine
    profiles: [ code_quality, phpstan ]
    working_dir: /project
    volumes:
      - "./:/project"
    command: [ phpstan, analyse, src ]

  php_qa-psalm:
    image: jakzal/phpqa:alpine
    profiles: [ code_quality, psalm ]
    working_dir: /project
    volumes:
      - "./:/project"
    command: [ psalm ]
